strictness: high
test-warnings: true
doc-warnings: false
member-warnings: false
inherits:
  - default
ignore-paths:
  - docs
ignore-patterns:
  - (^|/)skip(this)?(/|$)
autodetect: true
max-line-length: 120

pep8:
  full: true

dodgy:
  run: true

pycodestyle:
  enable:
  - W291

